# Generated by Django 3.2.5 on 2021-11-20 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_img', models.ImageField(upload_to='porduct')),
                ('p_img1', models.ImageField(blank=True, upload_to='porduct')),
                ('p_img2', models.ImageField(blank=True, upload_to='porduct')),
                ('price', models.DecimalField(decimal_places=0, max_digits=7)),
                ('name', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('date_posted', models.DateField(auto_now=True)),
                ('p_state', models.CharField(max_length=100)),
                ('p_city', models.CharField(max_length=100)),
                ('cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
