# Generated by Django 3.2.5 on 2021-11-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(blank=True, default='awatar.jpg', upload_to='media/profile'),
        ),
    ]
